version: "3.8"

services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - .:/srv/node/app
            - /srv/node/app/node_modules
        stdin_open: true
        tty: true
